# /etc/nginx/nginx.conf
user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';

    gzip on;
    gzip_types text/css application/javascript text/plain text/xml;

    port_in_redirect          off;
    server_name_in_redirect   off;

    server {
        listen       80 default_server;
        server_name  _;

        root /usr/share/nginx/html;

        error_page 404 /404.html;

        # Prevent default 404
        location = /404.html {
            internal;
        }
        location = /404 {
            internal;
        }

        location / {
            # Instead of /docs/index.html next uses /docs.html
            try_files $uri $uri.html $uri/index.html =404;
        }

        # Cache images
        location ~* \.(css|js|jpg|jpeg|png|gif|svg|ico)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
