name: Build and deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    permissions:
      contents: read
      packages: write
    uses: itsektionen/andesite/.github/workflows/v1.yml@main
    secrets: inherit
    with:
      deploy-dir: docs