name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run types:check
      - run: npm run build

  build-and-deploy:
    if: github.event_name == 'push'
    needs: validate
    permissions:
      contents: read
      packages: write
    uses: itsektionen/andesite/.github/workflows/v1.yml@main
    secrets: inherit
    with:
      deploy-dir: docs
